name: workstation_commander
description: A voice assistant for workstation management
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: "^4.5.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family:  Icons
      fonts:
      - asset: asset/icons/github.ttf
